# /wordpress-docker/docker-compose.yml
---
version: '3.3'
services:
  db:
    container_name: 'tgm-local-wordpress-db'
    image: 'mysql:5.7'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306    
    environment:
      MYSQL_ROOT_PASSWORD: mysql_tgm_pwd
      MYSQL_DATABASE: wp_tgm_db
      MYSQL_USER: wp_tgm_user
      MYSQL_PASSWORD: mysql_tgm_pwd
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"

  wordpress:
    container_name: 'tgm-local-wordpress'
    depends_on:
      - db
    image: 'wordpress:5.5.0-php7.3-apache'
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wp_tgm_user
      WORDPRESS_DB_PASSWORD: mysql_tgm_pwd
      WORDPRESS_DB_NAME: wp_tgm_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./tagmate-plugin:/var/www/html/wp-content/plugins/tagmate"
